trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
#  imageRepository: 'mycontainer'
  containerRegistry: 'testreg2022.azurecr.io'
#  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  dockertag: '$(Build.BuildId)'


steps:
# - task: NodeTool@0
#   inputs:
#     versionSpec: '16.x'
#   displayName: 'Install Node.js'

# - script: |
#     npm install
#     npm run build
#   displayName: 'npm install and build'


- task: Docker@2
  inputs:
    command: 'build'
    Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    tags: |
      $(tag)

- task: Docker@2
  inputs:
    containerRegistry: 'acr'
    repository: 'react-app'
    command: 'push'
    tags: |
      $(tag)





